[package]
name = "tiproxy-rs"
description = "TiProxy Rust dataplane executable"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[features]
default = []

[dependencies]
control-proto.workspace = true
dataplane.workspace = true
tokio.workspace = true

[lints]
workspace = true
