[package]
name = "tiproxy-rs"
description = "TiProxy Rust dataplane executable"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[features]
default = []

[dependencies]
control-config.workspace = true
control-etcd.workspace = true
control-external.workspace = true
control-plane.workspace = true
control-proto.workspace = true
control-topology.workspace = true
dataplane.workspace = true
if-addrs.workspace = true
libc.workspace = true
tokio = { workspace = true, features = ["signal"] }

[lints]
workspace = true
