[package]
name = "proxy-io"
description = "Transport ownership for the TiProxy Rust dataplane"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]
mysql-wire.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
flate2.workspace = true

[lints]
workspace = true
